apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Можно хранить отдельные ключи
  DB_PORT: "5432"
  DB_HOST: "db"
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres