apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: app #какие поды под какой меткой подконтрольны
  template:
    metadata:
      labels:
        app: app #метка для под
    spec:
      serviceAccountName: vault-auth
      imagePullSecrets:
        - name: gitlab-registry-key
      initContainers:
        - name: vault-fetcher
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args: #можно в конец еще добавить sleep 3600 для анализа содержимого init-sidecar контейнера
            - |
              apk add --no-cache curl jq

              echo "--- Get VAULT_TOKEN ---"
              JWT_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              RESPONSE=$(curl --request POST --data "{\"jwt\": \"$JWT_TOKEN\", \"role\": \"app-role\"}" $VAULT_ADDR/v1/auth/kubernetes/login)

              if [ -z "$RESPONSE" ] || [ "$RESPONSE" == "null" ]; then
                  echo "ERROR: Vault returned empty response"
                 exit 1
              fi

              if echo "$RESPONSE" | jq -e '.errors' > /dev/null; then
                  echo "ERROR: Vault returned API error:"
                  echo "$RESPONSE" | jq '.errors'
                  exit 1
              fi

              VAULT_TOKEN=$(echo "$RESPONSE" | jq -r '.auth.client_token')


              echo "--- Checking connection to Vault ---"
    
              RESPONSE=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/minikube_secret/data/app-service)
    
              echo "Raw response from Vault: $RESPONSE"
    
              if [ -z "$RESPONSE" ] || [ "$RESPONSE" == "null" ]; then
                  echo "ERROR: Vault returned empty response"
                 exit 1
              fi

              if echo "$RESPONSE" | jq -e '.errors' > /dev/null; then
                  echo "ERROR: Vault returned API error:"
                  echo "$RESPONSE" | jq '.errors'
                  exit 1
              fi

              echo "spring:
                datasource:
                  username: $(echo $RESPONSE | jq -r .data.data.username)
                  password: $(echo $RESPONSE | jq -r .data.data.password)" > /vault/secrets/application-vault.yaml

              echo "SUCCESS: Secrets written to /vault/secrets/application-vault.yaml"
          env:
            - name: VAULT_ADDR
              value: "http://vault-server:8200"
          volumeMounts:
            - name: secret-storage
              mountPath: /vault/secrets
      containers:
      - name: app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: SPRING_CONFIG_ADDITIONAL_LOCATION
            value: "file:/vault/secrets/application-vault.yaml"
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8082 #это порт которое слушает приложение фактически
        startupProbe: 
          httpGet:
            path: /test_project/actuator/health/liveness
            port: 8082
          failureThreshold: 30
          periodSeconds: 2
        readinessProbe: #анализирует готовность приложения отвечать на запросы
          httpGet:
            path: /test_project/actuator/health/readiness # должен содержать server.servlet.context-path
            port: 8082
          initialDelaySeconds: 10 #первая проверка наступит через n секунд после старта контейнера
          periodSeconds: 10 # делаем ретраи проверок каждые n секунд до первого успеха или failure раз (по умолчанию 3 раза, смотрим через kubectl describe pod)
        livenessProbe: #проверка залипания приложения, если не отвечает то перезагружаем
          httpGet:
            path: /test_project/actuator/health/liveness # должен содержать server.servlet.context-path
            port: 8082
          initialDelaySeconds: 15 # по сути первая проверка после отработки readinessProbe время первого запуска тут readinessProbe.initialDelaySeconds + readinessProbe.periodSeconds
        volumeMounts:
          - name: secret-storage
            mountPath: /vault/secrets
      volumes:
        - name: secret-storage
          emptyDir: {}
