apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app #какие поды под какой меткой подконтрольны
  template:
    metadata:
      labels:
        app: app #метка для под
    spec:
      imagePullSecrets:
        - name: gitlab-registry-key
      containers:
      - name: app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8082 #это порт которое слушает приложение фактически